# Generated by Django 5.2.1 on 2025-05-22 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                        verbose_name='name',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code='invalid_email',
                                message='Email cannot contain spaces.',
                                regex='^[^\\s]*$',
                            )
                        ],
                        verbose_name='email address',
                    ),
                ),
                (
                    'access_token',
                    models.CharField(blank=True, max_length=255, verbose_name='access token'),
                ),
                (
                    'refresh_token',
                    models.CharField(blank=True, max_length=255, verbose_name='refresh token'),
                ),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
